### ISSUE TITLE
continue 2 / break - php version

### ISSUE THREAD

**Issue by Ark74** [aurovrata/cf7-grid-layout#10]
With the deprecation of PHP 5.6 and 7.0, I've moved to a more recent php version and I'm looking at recurrent warnings.

My guess is that is related to the newer php version, seems to be the only warnings related to the continue function.

```
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in ~/cf7-grid-layout/public/class-cf7-grid-layout-public.php on line 1098

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in ~/cf7-grid-layout/public/class-cf7-grid-layout-public.php on line 1496
```

Are there plans to upgrade the php support for newer releases?
Thanks in advance for the attention.
Cheers!

**Comment by aurovrata** [comment]
Hello Luis

> My guess is that is related to the newer php version

no, this warning comes in all versions.  It is due to a line that forces a break from a switch statement by contiunue-ing the outer for loop.  Its quite normal and intentional.

Fyi, the plugin is developed using php 7.3, although currently there are no php 7+ specific structures that used and therefore the plugin code is compatible with 5.6 as well.

**Comment by Ark74** [comment]
All right then. Thanks.
