### ISSUE TITLE
v5.0.0beta2: Bug on creating new form

### ISSUE THREAD

**Issue by wiliamjk** [aurovrata/cf7-grid-layout#35]
I just installed beta2 and got an error

"The editor failed to load." See: https://snipboard.io/a3IDsn.jpg 

When I click in ok, I see this:

There is a Javascript error on the page which prevents the editor from loading properly.
Uncaught TypeError: $(...).toggles is not a function
(file: http://sandbox.local/wp-admin/load-scripts.php?c=1&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils&ver=6.1.1, line: 2
TypeError: $(...).toggles is not a function)

See: https://snipboard.io/dCrYut.jpg

**Comment by aurovrata** [comment]
can you inspect your console and give me the error line number in the plugin js file.

jquery-toggles are out in v5 and replaced with pure CSS ones instead.

It is possible your browser is caching the js file?

**Comment by aurovrata** [comment]
I just released [beta3](https://github.com/aurovrata/cf7-grid-layout/releases/tag/v5.0.0beta3) with the changes from this week.

You will need to create a new form (existingforms created with beta1/beta2 versions will no longer work).  

v5 now uses different row/columns class names in order to remove clashes with some themes that users reported in v4

**Comment by wiliamjk** [comment]
The bugs seem to be resolved in beta3!
